sudo: required
services:
  - docker

before_install:
  - docker build -t sbkumaran/docker-react -f DockerFile.dev .

script:
  - docker run -e CI=run sbkumaran/docker-react npm run test -- --coverage

# contains a bunch of instruction to deploy them them AWS
deploy:
  provider: "elasticbeanstalk"
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env-1"
  bucket_name: "elasticbeanstalk-us-east-2-295981522053"
  bucket_path: "docker-react"
  on:
    branch: master
  # this is for AWS access
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"


